### ISSUE TITLE
Setting additional groups not working

### ISSUE THREAD

**Issue by Lemelisk** [Oefenweb/ansible-user#4]
I'm trying to set up users/groups using your role. This works perfectly for most parts, but setting additional groups for a user fails every time.

To me this seems to be some parsing problem. Trying to add a user to group "sudo" fails with the message "Group s does not exist", adding to groups "sudo,plugdev" results in "Group e does not exist"

I use the following (simplified sample-)playbook

``` YAML
- name: add users and groups
  hosts: vmonitor
  #become: yes
  sudo: yes
  vars:
    - user_groups:
       - name: testuser
         gid: 1100
         state: present
    - user_users:
       - name: testuser
         uid: 1100
         group: testuser
         groups: sudo
         state: present
  roles:
   - tersmitten.user
```

This is the resulting output:

``` ShellSession
ansible@vadmin:~/ansible-playbooks$ ansible-playbook create-users
PLAY [Update and upgrade all VMs] ********************************************* 

GATHERING FACTS *************************************************************** 
ok: [vmonitor]

TASK: [tersmitten.user | groups | add / delete] ******************************* 
skipping: [vmonitor] => (item={'state': 'present', 'gid': 1100, 'name': 'testuser'})

TASK: [tersmitten.user | groups | add / delete (with GID)] ******************** 
changed: [vmonitor] => (item={'state': 'present', 'gid': 1100, 'name': 'testuser'})

TASK: [tersmitten.user | groups | add (user)] ********************************* 
ok: [vmonitor] => (item={'state': 'present', 'group': 'testuser', 'name': 'testuser', 'groups': 'sudo', 'uid': 1100})

TASK: [tersmitten.user | users | add / delete] ******************************** 
skipping: [vmonitor] => (item={'state': 'present', 'group': 'testuser', 'name': 'testuser', 'groups': 'sudo', 'uid': 1100})

TASK: [tersmitten.user | users | add / delete (with UID)] ********************* 
failed: [vmonitor] => (item={'state': 'present', 'group': 'testuser', 'name': 'testuser', 'groups': 'sudo', 'uid': 1100}) => {"failed": true, "item": {"group": "testuser", "groups": "sudo", "name": "testuser", "state": "present", "uid": 1100}}
msg: Group s does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ansible/create-users.retry

vmonitor                   : ok=5    changed=1    unreachable=0    failed=1
```
